Feat: Added Giphy embed
outline/outline pull request #3394
Opened 2022-04-15 16:05 UTC by Akash-Ramjyothi

## Description:

Added a feature to easily embed a GIF. Giphy helps to accomplish the same in the most efficient manner.

2022-04-15 16:35 UTC, tommoor requested changes

2022-04-15 16:35 UTC, tommoor commented on app/embeds/Giphy.js
> +// @flow
We moved over to Typescript quite a while ago now, all types should be Typescript and all file extensions should be `.ts`

2022-04-15 16:35 UTC, tommoor commented on shared/editor/embeds/index.tsx
> +    icon: () => <Img src="/images/giphy.png" />,
Need the matching image for this

2022-06-09 19:43 UTC, closed without merging

2022-06-29 04:58 UTC, dkkb commented
Great job.